mlibrary/chipmunk

- app/models/bag.rb
- app/models/request.rb
- spec/models/audio_bag_spec.rb
- spec/models/digital_bag_spec.rb
- spec/support/examples/a_bag.rb
- spec/support/examples/a_request.rb
Was returning :bag_id but should have returned bag_id. The existing
tests didn't catch this issue because both the tests and the code used
e.g. v1_request_url to check the returned URLs.
> fix url generation for bags & requests

- app/controllers/v1/requests_controller.rb
- app/models/bag.rb
- app/models/request.rb
- app/models/user.rb
- config/application.rb
- config/upload.yml
- db/migrate/20170530181632_add_username_to_users.rb
- db/migrate/20170531155509_add_unique_constraints_to_requests.rb
- db/migrate/20170531160317_remove_upload_link_from_requests.rb
- db/schema.rb
- lib/request_builder.rb
- spec/controllers/v1/requests_controller_spec.rb
- spec/fabricators/request_fabricator.rb
- spec/fabricators/user_fabricator.rb
- spec/models/audio_bag_spec.rb
- spec/models/audio_request_spec.rb
- spec/models/digital_bag_spec.rb
- spec/models/digital_request_spec.rb
- spec/models/user_spec.rb
- spec/request_builder_spec.rb
- spec/support/examples/a_bag.rb
- spec/support/examples/a_request.rb
Requests - upload path, link, specs
- Adds username to user - required for constructing the upload path.
- Uses strong parameters in requestcontroller
- Gets user from current_user
- Consistently uses "external_id" instead of "mirlyn_id"
- Uses 'create' instead of 'build' and passes parameters to create instead
of new. This more closely matches the convention for a factory
that saves the thing it makes.
- Continues to just pass the request parameters through the factory to
the object initializer. I tried some things with keyword args, but the
way Rails handles parameters vs. the Ruby keyword args makes it messy to
marshal/unmarshal things that just end up getting passed through to the
object constructor anyway.
> requests: upload link, specs, etc

- app/views/v1/bags/_bag.json.jbuilder
- spec/views/v1/bags/index.json.jbuilder_spec.rb
- spec/views/v1/bags/show.json.jbuilder_spec.rb
Previously we tried to get the external_service name from
the bag model. This changes the views to simply render
the field as 'external_id'.
We're not using this now, no need to try to keep the machinery around.
> Render external_id as simply 'external_id'

- app/controllers/v1/queue_items_controller.rb
- app/jobs/bag_move_job.rb
- lib/uploader.rb
- spec/controllers/v1/queue_items_controller_spec.rb
- spec/jobs/bag_move_job_spec.rb
- Specs for BagMoveJob including its error handling
- `BagMoveJob` logs the error in its `QueueItem`
- On failure, CLI dumps the `QueueItem` including its error
- On success, CLI dumps the `Bag`
> queue item error reporting

- app/jobs/bag_move_job.rb
- app/models/bag.rb
- config/validation.yml
- lib/queue_item_builder.rb
- spec/jobs/bag_move_job_spec.rb
- spec/models/bag_spec.rb
- spec/queue_item_builder_spec.rb
In BagMoveJob, get the bag's source (upload) path and destination
(storage) path directly from the bag rather than passing as
parameters to BagMoveJob.
Also, consistently name these things "src_path" and "dest_paths" in
models, jobs, and tests. "upload path" and "storage path" should refer
to the base directories in the config only. Bag#storage_location should
refer to where an ingested bag actually is, not where it should go.
An alternative to this would be to instead continue passing the source &
destination paths to the BagMoveJob and instead have the validation
command use the source path from the BagMoveJob. That would imply bags
shouldn't know what their upload & storage paths are which seems counter
ot the intention of merging Bag and Request.
> Bag knows its own storage paths

- Rakefile
- config/initializers/resque.rb
- spec/support/fixtures/audio/upload/good/chipmunk-info.txt
- spec/support/fixtures/audio/upload/good/tagmanifest-md5.txt
- spec/support/fixtures/audio/upload/good/tagmanifest-sha1.txt
Set up resque to use the correct namespace when enqueuing jobs.
Correct external identifier in bag fixture
> resque setup; successful dev mode full stack testing

- app/models/bag.rb
- app/views/v1/bags/_bag.json.jbuilder
- lib/uploader.rb
- spec/features/end_to_end.feature
- spec/support/step_definitions/request_steps.rb
- spec/upload_spec.rb
- spec/uploader_spec.rb
- spec/views/v1/bags/a_bag_view.rb
completely revamped version of the intention from #23 - adds a "stored?" method on the bag, exposes that in the view, and checks it when uploading.
> PFDR-80 - don't upload if bag is already uploaded

- lib/uploader.rb
- spec/uploader_spec.rb
Needed to re-work some of the specs so that things worked as expected here (see PFDR-79 for the particular bug the previous fixtures were running into)
> PFDR-82: output status & error instead of json dump of queue item

- config/upload.yml
- spec/support/examples/a_validation_integration.rb
- spec/turnip_helper.rb
Also: use a test upload/storage path by default that's more likely to be writable
> Fix issues with Rails application config getting overwritten in tests

- README.md
- bin/upload
- config/client.yml.example
- lib/chipmunk_cli.rb
- lib/tasks/chipmunk_setup.rake
- lib/uploader.rb
- spec/uploader_spec.rb
- adds argument parsing & config loading in ChipmunkCLI (w/o specs)
- loads configuration (url and api key) from config/client.yml by
default & takes a config parameter
- updates chipmunk:setup rake task to use config/client.yml
- slightly changes display output format
- start to flesh out README
- fix bug in PFDR-82 specs & test (was using symbol instead of string
for hash key)
> PFDR-83: Ability to batch upload material

- app/jobs/bag_move_job.rb
- spec/chipmunk_bag_validator_spec.rb
- spec/jobs/bag_move_job_spec.rb
follow-up to #30 to split up the `BagMoveJob` & `ChipmunkBagValidator` specs
> split up BagMoveJob & ChipmunkBagValidator specs

- app/controllers/v1/bags_controller.rb
- spec/controllers/v1/bags_controller_spec.rb
Allows the bag show endpoint to retrieve bags by external ID.
Although the external ID could in theory conflict with the internal ID, that should be rare.
I'm still interested in feedback on whether this is a reasonable way to do it - the alternative I suppose would be to create a route like `/bags/external_id/:external_id`, but I'm not really sure what would be the properly RESTful way to do that.
> PFDR-89: Retrieve bags by external ID

- app/controllers/v1/events_controller.rb
- app/controllers/v1/packages_controller.rb
- app/controllers/v1/queue_items_controller.rb
- spec/controllers/v1/audits_controller_spec.rb
- spec/controllers/v1/events_controller_spec.rb
- spec/controllers/v1/packages_controller_spec.rb
- spec/controllers/v1/queue_items_controller_spec.rb
- spec/policies/policy_helpers.rb
- spec/support/examples/an_index_endpoint.rb
Adds a couple of helpers that mock the policy. It would be nicer to be able to inject a policy, but controller specs make this hard. Longer-term, we could think about adding something similar to Pundit where the controller raises an error if the policy wasn't checked, but this meets the need for now. This doesn't add anything with respect to ensuring the scope was properly resolved, but there are existing controller specs that cover that, albeit using the real policy rather than a mock one.
> PFDR-99: Test policies are checked in controller actions

- app/controllers/v1/queue_items_controller.rb
- app/models/queue_item.rb
- docs/v1/queue.rst
- spec/controllers/v1/queue_items_controller_spec.rb
This is set to merge to the docs branch for PFDR-121 / #51 as I included the documentation changes there.
I think it's reasonable to sit on this until PFDR-98 / #50 is merged.
> PFDR-133 - See queue items for a given package

- spec/requests/v1/events_index_spec.rb
- spec/requests/v1/packages_file_spec.rb
- spec/requests/v1/packages_index_spec.rb
- spec/requests/v1/queue_items_index_spec.rb
- there's a fair bit of repetition between these specs and they could
certainly be cleaned up, but we are trying to favor readability over
including a lot of shared contexts etc
- skip specs for attempting to get events or queue item for a package of
an unauthorized type, pending PFDR-175
> PFDR-168 - integration tests for collection policy specs

- .simplecov
- Dockerfile
- docker-compose.yml
- docs/contributing.rst
Resolves PFDR-160
Resolves PFDR-204
Run with `docker-compose run web bash`
I _think_ this all the dependencies working, but that may not be the case. That's difficult to determine until we can get the integration tests passing.
> Create docker image with dependencies for integration tests

- features/step_definitions/deposit_steps.rb
- features/support/world_extensions.rb
This adds a couple of prospective conveniences for writing scenarios,
specifically around creating an acting user with a particular role and
making API requests (with the "me" user's API token header).
> Add World modules for users/API requests

- app/models/package.rb
- config/initializers/services.rb
- config/settings/test.yml
- features/deposit_an_artifact.feature
- features/reject_an_artifact.feature
- features/step_definitions/more_steps.rb
- lib/chipmunk/incoming_storage.rb
- lib/chipmunk/package_storage.rb
- spec/all_support.rb
- spec/chipmunk/incoming_storage_spec.rb
- spec/chipmunk/package_storage_spec.rb
- spec/features/end_to_end.feature
- spec/integration/audio_spec.rb
- spec/integration/video_spec.rb
- spec/support/bin/validate_audio.sh
- spec/support/bin/validate_video.sh
- spec/support/examples/a_validation_integration.rb
- spec/support/fixtures/bad_test_bag/bag-info.txt
- spec/support/fixtures/bad_test_bag/bagit.txt
- spec/support/fixtures/bad_test_bag/chipmunk-info.txt
- spec/support/fixtures/bad_test_bag/data/samplefile
- spec/support/fixtures/bad_test_bag/manifest-md5.txt
- spec/support/fixtures/bad_test_bag/manifest-sha1.txt
- spec/support/fixtures/bad_test_bag/tagmanifest-md5.txt
- spec/support/fixtures/bad_test_bag/tagmanifest-sha1.txt
This wraps up the depositing and upload features. The primary difficulty stemmed from the mismatch between the upload_link and the upload_path; the logic was assumed production's environment, so performing pseudo-uploads in the acceptance tests was next to impossible.
The primary approach I took was to move the upload_link responsibility to IncomingStorage via dependency injection, thereby allowing for the same behavior to achieve both production's needs and our tests. No changes are required in prod, and the tests that exercised that behavior are still in place.
Each commit is pursuant the above goals and strategy.
> Deposit tests

- Gemfile.lock
They call it a minor version update but the thing completely breaks if you're not on the exact same version. We have 2.0.2 on servers so this is basically required.
> Update bundler 2.0.1 -> 2.0.2

- config/initializers/services.rb
This is the minimal fix for the problem of no incoming uploads resolving. It does not treat the peculiarity that the argument is called root_path, nor the inconsistency between UploadPath (which works on paths directly) and UserUploadPath (which only works within the incoming storage volume)... but it does what we need.
> PFDR-231 - Use relative paths for incoming packages

- Gemfile.lock
This is a workaround for the system puma dependency mismatch issue. You'll need to redeploy the application from deployhost after merging.
> Update nio4r to 2.5.1

- bin/validate_bentleyaudio.sh
- config/settings/development.yml
- config/settings/test.yml
- config/validation.yml
- spec/support/bin/validate_bentleyaudio.sh
With the separate content type, it's easiest to have a separate driver
script for validation. We could extract pieces or do parameter parsing,
but I want to leave that for when we consider if there are variants of
content types or not. For now, it is only apparent duplication.
> PFDR-265 - Add validate_bentleyaudio

- lib/tasks/restart_jobs.rake
We've seen Resque jobs crash occasionally, which leaves QueueItems in
pending status but with nothing in the queue, so they are permanently
orphaned. It's apparently because of some strange threading deadlock
with semantic_logger. Those we have enqueued again have finished.
This rake task is intentionally naive. It checks for pending jobs and
the queue. If there are no jobs running but any are marked pending, they
are considered stranded and the oldest is put back into the queue.
> PFDR-277 - Add rake task to restart lost jobs
